string request_id
sensor_msgs/CompressedImage image
sensor_msgs/RegionOfInterest roi
sensor_msgs/RegionOfInterest target_roi
obstacle_traversal_interfaces/VehicleState vehicle_state
---
obstacle_traversal_interfaces/PushabilityAssessment assessment
---
uint8 PERCEPTION=1
uint8 DECISION=2
uint8 state
string message
